---
- name: add add-apt-repostory
  apt: pkg=software-properties-common state=present update_cache=yes
    
- name: add add-apt-repostory
  apt: pkg=python-software-properties state=present update_cache=yes
  when: ansible_distribution_release == "precise"

- name: add webupd8 ppa
  apt_repository: repo='ppa:webupd8team/java' update_cache=yes

- name: auto accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: install java8 packages
  apt: name={{ item }}
  with_items:
      - oracle-java8-installer
      - ca-certificates
